### ISSUE TITLE
Feedback and request for re-encryption

### ISSUE THREAD

**Issue by azc5OQ** [ProjectOpenOrbit/do-swf-decryptor#2]
just tried it, works
I checked how the swf is decrypted, I do not think I could have figured it out, so nice work
I wonder why kotlin as language, but still nice work

**Comment by melover43** [comment]
The decryption process works very well. It would be great if you could also add a method that re-encrypts the data

**Comment by ertaytw** [comment]
just tried it, not working.

Downloaded the files and then decrypted them but main.swf won't open and main_decrypted.swf is still encrypted.

**Comment by tram98** [comment]
Hey @azc5OQ,

thanks for the feedback (and sorry for responding over a **year** late, i did not get a notification for this PR), I am happy to read you like it :)
I chose Kotlin for three reasons:
1. I use the JPEX Free Flash Decompiler library (written in Java) to disect the SWF files and produce deobfuscated source code.
2. I wanted to learn more about Kotlin
3. Kotlin has less boilerplate than Java, which I like very much :)

I hope I could clear things up!

Regards,
tram98

**Comment by tram98** [comment]
Hey @melover43,
I'm glad to hear the tool is working well for you! 😊

However, regarding your request for a re-encryption feature, there are some significant challenges:

1. **Encryption Algorithm**: One of the encryption algorithms remains unclear to me; thus, I am only capable of **decrypting**, not encrypting.
2. **File Hash Signature**: Re-encrypting a patched SWF file alters its hash signature. This modified hash is checked by the `loadingscreen.swf` file, meaning this file would also need patching, which complicates the process 😔.

Encryption methods in use for the SWF:
1. **RC4 Encryption Algorithm**:
   - Re-encryption with this algorithm is feasible.
2. **Custom Encryption Algorithm**:
   - The specifics of this algorithm are unknown as I only translated the code from ActionScript to Kotlin without understanding the underlying encryption method.

I hope you understand. If you want to look into the matter yourself, I would be glad to receive a pull request which implements this feature :)

Best,
tram98
